### ISSUE TITLE
Alignment issue on cards

### ISSUE THREAD

**Issue by stummjr** [eliasdorneles/usolitaire#1]
**Terminal:** iTerm2
**Dimensions:** 40 rows, 100 columns
**Font:** mononoki, 18pt

![screen shot 2017-04-22 at 18 16 18](https://cloud.githubusercontent.com/assets/1170435/25308323/d1c8ae06-2787-11e7-9662-7a84506b90fd.png)

**Comment by eliasdorneles** [comment]
Hm, sounds like an issue with the font.
Does the problem persist with other fonts as well?

**Comment by stummjr** [comment]
Nope, the issue is my font. ;)
