### ISSUE TITLE
Feature Request - Play with keys

### ISSUE THREAD

**Issue by cwaldbieser** [eliasdorneles/usolitaire#4]
It would be great if the game were actually playable with the keyboard.  The mouse is fine, but generally when I am in a terminal, I want to use the keyboard.

**Comment by eliasdorneles** [comment]
Hello Carl,

Thanks for trying out the game and giving feedback.

Indeed, that would be a great feature to add.
Someone actually already made [a PR with a draft implementation](https://github.com/eliasdorneles/usolitaire/pull/3).
I think the design of the keyboard shortcuts deserves some thinking / experimenting -- I left a comment there with my wishlist, but I'm open to suggestions. =)

**Comment by eliasdorneles** [comment]
I've implemented this as part of porting it to [Textual](https://textual.textualize.io/).

Check out the just released 1.0 version, with both mouse and keyboard support! =)
