### ISSUE TITLE
Toggle help crashes with `#help-text` NoMatches

### ISSUE THREAD

**Issue by TomJGooding** [eliasdorneles/usolitaire#6]
I love seeing Textual projects like these! 

Just to let you know that pressing `?` to toggle help crashes, as it looks like there's no widget with an id of `help-text`:

```
NoMatches: No nodes match <DOMQuery query='#help-text'>
```

**Comment by eliasdorneles** [comment]
Hello!

Ouch, I forgot to remove that -- thanks for reporting!
